name: meteor
services:
- name: web
  github:
    repo: Dufieng/Meteor
    branch: main
  build_command: npm ci
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
